### ISSUE TITLE
Ask users to write their bio in English

### ISSUE THREAD

**Issue by ssaunier** [lewagon/alumni#209]
Re-use the LanguageDetector component.

**Comment by Eschults** [comment]
For sure?
Si c'est juste à partager avec les classmates pourquoi pas les laisser rédiger leur bio en local ? 
T'imagines Elie rédiger sa life en anglais ? :sleeping: 
You tell me!

**Comment by ssaunier** [comment]
Pour anticiper sur le "réseau social" alumni où on l'affichera également :)
