### ISSUE TITLE
Bug when trying to edit the title of a post

### ISSUE THREAD

**Issue by ssaunier** [lewagon/alumni#241]
As an admin (or post creator), I can update a post title. The thing is that the text remains when I click on the "edit" button:

<img width="495" alt="screen shot 2016-06-16 at 10 02 23" src="https://cloud.githubusercontent.com/assets/414418/16109503/79fb0ade-33a9-11e6-8850-c7d1d48a0de2.png">

**Comment by krokrob** [comment]
Sounds like a `ondemand`issue 😜

**Comment by ssaunier** [comment]
Ah ah at least I put a screenshot ;)

-- 
Sébastien Saunier
http://saunier.me
