### ISSUE TITLE
page edit des villes pour drivers

### ISSUE THREAD

**Issue by monsieurpaillard** [lewagon/alumni#255]
@krokrob sur cette page http://alumni.lewagon.org/cities/lyon/edit les drivers ne peuvent pas modifier le texte qui est juste en dessous. Le "description Fr" dans l'admin.

**Comment by krokrob** [comment]
@monsieurpaillard je ne comprends pas ce qu'il ne peuvent pas modifier. Le texte qui est juste en-dessous de quoi?

**Comment by ssaunier** [comment]
Non ce sont deux champs de description de la ville mais ils sont pas encore dans la page edit en fait (description_fr, description_en)

**Comment by krokrob** [comment]
@ssaunier tu voulais pas je crois

**Comment by krokrob** [comment]
<img width="1280" alt="capture d ecran 2016-08-24 a 13 45 31" src="https://cloud.githubusercontent.com/assets/9978111/17929474/1339e4a8-6a01-11e6-9126-a6bac6eaf56d.png">

**Comment by krokrob** [comment]
on parle de cette phrase-là?

**Comment by ssaunier** [comment]
Non, celle la:

**Comment by krokrob** [comment]
@ssaunier je ne peux pas suivre ton lien

**Comment by ssaunier** [comment]
Duplicate of #244
