### ISSUE TITLE
CORS Policy

### ISSUE THREAD

**Issue by vrehm** [lewagon/alumni#271]
Some ressources are buggy, see my screenshot
<img width="1271" alt="capture d ecran 2016-12-15 20 25 56" src="https://cloud.githubusercontent.com/assets/8135206/21238803/b20f3de2-c304-11e6-8388-aa93772157a4.png">

**Comment by ssaunier** [comment]
Closing because of [sunset](https://github.com/lewagon/alumni/issues/280)
